[deps]
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"
